### ISSUE TITLE
Parameters to excludes custom words

### ISSUE THREAD

**Issue by service-paradis** [bubkoo/potential-duplicates#14]
Thanks for this action!

I would like to use something similar for https://github.com/simple-icons/simple-icons

It would be really beneficial if we could filter some words of the algo. For example, we have a lot of request that looks like `Request: brandname icon`. There would be a lot of false positive if we use your action as-is. But if we could exclude specific words like `Request` and `icon`, it could probably be able to catch a good amount of duplicate.

**Comment by bubkoo** [comment]
@service-paradis `filter` input is supported [in the next release](https://github.com/bubkoo/potential-duplicates/releases/tag/v1.0.2). Any newly created issue would stop detection when it's title match the filter. And filter can be a string or space separated strings work with https://www.npmjs.com/package/anymatch.

**Comment by service-paradis** [comment]
@bubkoo Thanks for your work and the follow up!
The changes is great. It is not exactly what I need though.

This is an examples.

- if I open `Request Ubuntu icon` and `Request Fedora icon`, they will be flagged as potential duplicates

I would like the algo to exclude a custom list of words before comparing the title. For example, having something like:
```
excludes:
  - Request
  - icon
```
- This way, the algo will compare ~~Request~~ `Ubuntu` ~~icon~~ with ~~Request~~ `Fedora` ~~icon~~. They wont be flagged as potential duplicates
- If I have a title `Ubuntu icon` and `Request Ubuntu icon`, the algo will compare `Ubuntu` ~~icon~~ with ~~Request~~ `Ubuntu` ~~icon~~. They will be flagged as potential duplicates

**Comment by bubkoo** [comment]
@service-paradis config like this
```yaml
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          filter: 'Request ** icon'
```

And this is my tested issues #15 #16

**Comment by service-paradis** [comment]
Thanks again @bubkoo 😄 
Since people are not that disciplined, would it also work for other derivation than the current filter?
Example, people can request icons using these kind of title:

- Request: Ubuntu icon
- Request Ubuntu icon
- Request: Ubuntu
- Request Ubuntu
- Add Ubuntu icon
- Add Ubuntu
- Ubuntu icon
- Ubuntu
- ...

**Comment by bubkoo** [comment]
@service-paradis You can specify multi filters in each line, such as
```yml
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          filter: |
            Request ** icon
            Add ** icon
            ** icon **
            ** Ubuntu **
```

**Comment by mondeja** [comment]
Sorry @bubkoo, but this is not what we need.

If I'm not mistaken, when an issue is opened, if match with, at least, one filter ([if their title is "valid"](https://github.com/bubkoo/potential-duplicates/blob/7f95e44e9aac384e6b29aaf5746c539a9b81f7b9/src/action.ts#L15)) will not be checked for potential duplicates. We need that, regardless of the opened issue title (without "validate it"), remove from it the words that are not needed and, comparing with other titles, of these other titles would be also removed certain words to improve the match between titles.

As @service-paradis pointed, we need an "exclude" function. Is something that you plan to include or not?

**Comment by bubkoo** [comment]
@mondeja @service-paradis Keyworlds specified in `exclude` will be replaced with empty string before detecting.

```yml
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            request
            icon
            add
            ubuntu
```
